server:
  port: 8088
  host: 127.0.0.1

spring:
  application:
    name: melon
  codec:
    max-in-memory-size: 50MB

melon:
  home_dir: ~/.melonAI

logging:
  level:
    com.melon: INFO
    io.agentscope: INFO
